"""add state metadata columns

Revision ID: 28443ecee2cf
Revises: e8b1a50435f5
Create Date: 2026-02-27 17:13:37.632059

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '28443ecee2cf'
down_revision: Union[str, Sequence[str], None] = 'e8b1a50435f5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('states', sa.Column('fips_code', sa.String(length=2), nullable=True))
    op.add_column('states', sa.Column('region', sa.String(length=50), nullable=True))
    op.add_column('states', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.alter_column('states', 'abbrev',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.String(length=2),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('states', 'abbrev',
               existing_type=sa.String(length=2),
               type_=sa.VARCHAR(length=10),
               existing_nullable=False)
    op.drop_column('states', 'created_at')
    op.drop_column('states', 'region')
    op.drop_column('states', 'fips_code')
    # ### end Alembic commands ###
