"""rich text fields

Revision ID: 3698aa5f4b1e
Revises: 
Create Date: 2026-02-26 19:11:58.799216

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3698aa5f4b1e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ahjs', sa.Column('guidelines', sa.Text(), nullable=True))
    op.add_column('labels', sa.Column('description', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('labels', 'description')
    op.drop_column('ahjs', 'guidelines')
    # ### end Alembic commands ###
