"""add requested domain tables and links

Revision ID: e8b1a50435f5
Revises: d79dcd556730
Create Date: 2026-02-27 17:08:49.315647

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e8b1a50435f5'
down_revision: Union[str, Sequence[str], None] = 'd79dcd556730'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ahjs', sa.Column('name', sa.String(length=255), nullable=True))
    op.add_column('ahjs', sa.Column('county', sa.String(length=255), nullable=True))
    op.add_column('ahjs', sa.Column('city', sa.String(length=255), nullable=True))
    op.add_column('ahjs', sa.Column('fireset_back', sa.Float(), nullable=True))
    op.add_column('ahjs', sa.Column('jurisdiction_type', sa.String(length=100), nullable=True))
    op.add_column('ahjs', sa.Column('phone', sa.String(length=50), nullable=True))
    op.add_column('ahjs', sa.Column('email', sa.String(length=255), nullable=True))
    op.add_column('ahjs', sa.Column('website', sa.String(length=500), nullable=True))
    op.add_column('ahjs', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.execute("UPDATE ahjs SET name = COALESCE(ahj_name, 'Unknown AHJ') WHERE name IS NULL")
    op.execute("UPDATE ahjs SET state_id = (SELECT id FROM states ORDER BY id LIMIT 1) WHERE state_id IS NULL")
    op.alter_column('ahjs', 'name', existing_type=sa.VARCHAR(length=255), nullable=False)
    op.alter_column('ahjs', 'ahj_name',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('ahjs', 'state_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.add_column('code_types', sa.Column('title', sa.String(length=255), nullable=True))
    op.execute("UPDATE code_types SET title = COALESCE(key, 'Untitled Code Type') WHERE title IS NULL")
    op.alter_column('code_types', 'title', existing_type=sa.VARCHAR(length=255), nullable=False)
    op.alter_column('code_types', 'key',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.add_column('codes', sa.Column('code_amendments', sa.Integer(), nullable=True))
    op.add_column('codes', sa.Column('title', sa.String(length=255), nullable=True))
    op.add_column('codes', sa.Column('description', sa.Text(), nullable=True))
    op.add_column('codes', sa.Column('edition', sa.String(length=100), nullable=True))
    op.add_column('codes', sa.Column('applicable_code_category_id', sa.Integer(), nullable=True))
    op.add_column('codes', sa.Column('issuing_body', sa.String(length=255), nullable=True))
    op.add_column('codes', sa.Column('state_id', sa.Integer(), nullable=True))
    op.add_column('codes', sa.Column('adopted_at', sa.Date(), nullable=True))
    op.add_column('codes', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.execute("UPDATE codes SET title = COALESCE(code_name, 'Untitled Code') WHERE title IS NULL")
    op.alter_column('codes', 'title', existing_type=sa.VARCHAR(length=255), nullable=False)
    op.create_foreign_key(None, 'codes', 'states', ['state_id'], ['id'])
    op.create_foreign_key(None, 'codes', 'code_amendments', ['code_amendments'], ['id'])
    op.create_foreign_key(None, 'codes', 'applicable_code_categories', ['applicable_code_category_id'], ['id'])
    op.add_column('combination_mapper', sa.Column('category_id', sa.Integer(), nullable=True))
    op.add_column('combination_mapper', sa.Column('equipment_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'combination_mapper', 'categories', ['category_id'], ['id'])
    op.create_foreign_key(None, 'combination_mapper', 'equipment', ['equipment_id'], ['id'])
    op.add_column('formulas', sa.Column('title', sa.Text(), nullable=True))
    op.add_column('formulas', sa.Column('formula_link_type_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'formulas', 'formula_linker_types', ['formula_link_type_id'], ['id'])
    op.add_column('labels', sa.Column('upc_code', sa.String(length=100), nullable=True))
    op.add_column('labels', sa.Column('name', sa.String(length=255), nullable=True))
    op.add_column('labels', sa.Column('label_number', sa.String(length=100), nullable=True))
    op.add_column('labels', sa.Column('length', sa.Integer(), nullable=True))
    op.add_column('labels', sa.Column('width', sa.Integer(), nullable=True))
    op.add_column('labels', sa.Column('image_url', sa.String(length=500), nullable=True))
    op.add_column('labels', sa.Column('background_color', sa.String(length=100), nullable=True))
    op.add_column('labels', sa.Column('text_color', sa.String(length=100), nullable=True))
    op.add_column('labels', sa.Column('is_active', sa.Boolean(), server_default='1', nullable=False))
    op.add_column('labels', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.execute("UPDATE labels SET label_number = COALESCE(label_name, CONCAT('LBL-', id::text)) WHERE label_number IS NULL")
    op.alter_column('labels', 'label_number', existing_type=sa.VARCHAR(length=100), nullable=False)
    op.alter_column('labels', 'field_type',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.create_unique_constraint(None, 'labels', ['label_number'])
    op.create_unique_constraint(None, 'labels', ['upc_code'])
    op.add_column('notes', sa.Column('note_type_id', sa.Integer(), nullable=True))
    op.add_column('notes', sa.Column('page_no', sa.Integer(), nullable=True))
    op.add_column('notes', sa.Column('length', sa.Float(), nullable=True))
    op.add_column('notes', sa.Column('width', sa.Float(), nullable=True))
    op.add_column('notes', sa.Column('equipment_id', sa.Integer(), nullable=True))
    op.add_column('notes', sa.Column('section_no', sa.Integer(), nullable=True))
    op.alter_column('notes', 'code_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_foreign_key(None, 'notes', 'note_types', ['note_type_id'], ['id'])
    op.create_foreign_key(None, 'notes', 'equipment', ['equipment_id'], ['id'])
    op.add_column('utilities', sa.Column('name', sa.String(length=255), nullable=True))
    op.add_column('utilities', sa.Column('requirements', sa.Text(), nullable=True))
    op.add_column('utilities', sa.Column('state_id', sa.Integer(), nullable=True))
    op.add_column('utilities', sa.Column('eia_id', sa.String(length=100), nullable=True))
    op.add_column('utilities', sa.Column('utility_type', sa.String(length=100), nullable=True))
    op.add_column('utilities', sa.Column('service_territory', sa.String(length=255), nullable=True))
    op.add_column('utilities', sa.Column('phone', sa.String(length=50), nullable=True))
    op.add_column('utilities', sa.Column('website', sa.String(length=500), nullable=True))
    op.add_column('utilities', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.execute("UPDATE utilities SET name = COALESCE(utility_name, 'Unknown Utility') WHERE name IS NULL")
    op.execute("""
        UPDATE utilities u
        SET state_id = a.state_id
        FROM ahjs a
        WHERE u.ahj_id = a.id AND u.state_id IS NULL
    """)
    op.alter_column('utilities', 'name', existing_type=sa.VARCHAR(length=255), nullable=False)
    op.execute("UPDATE utilities SET state_id = (SELECT id FROM states ORDER BY id LIMIT 1) WHERE state_id IS NULL")
    op.alter_column('utilities', 'state_id', existing_type=sa.INTEGER(), nullable=False)
    op.alter_column('utilities', 'ahj_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('utilities', 'response_type',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.create_foreign_key(None, 'utilities', 'states', ['state_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'utilities', type_='foreignkey')
    op.alter_column('utilities', 'response_type',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('utilities', 'ahj_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('utilities', 'created_at')
    op.drop_column('utilities', 'website')
    op.drop_column('utilities', 'phone')
    op.drop_column('utilities', 'service_territory')
    op.drop_column('utilities', 'utility_type')
    op.drop_column('utilities', 'eia_id')
    op.drop_column('utilities', 'state_id')
    op.drop_column('utilities', 'requirements')
    op.drop_column('utilities', 'name')
    op.drop_constraint(None, 'notes', type_='foreignkey')
    op.drop_constraint(None, 'notes', type_='foreignkey')
    op.alter_column('notes', 'code_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('notes', 'section_no')
    op.drop_column('notes', 'equipment_id')
    op.drop_column('notes', 'width')
    op.drop_column('notes', 'length')
    op.drop_column('notes', 'page_no')
    op.drop_column('notes', 'note_type_id')
    op.drop_constraint(None, 'labels', type_='unique')
    op.drop_constraint(None, 'labels', type_='unique')
    op.alter_column('labels', 'field_type',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.drop_column('labels', 'created_at')
    op.drop_column('labels', 'is_active')
    op.drop_column('labels', 'text_color')
    op.drop_column('labels', 'background_color')
    op.drop_column('labels', 'image_url')
    op.drop_column('labels', 'width')
    op.drop_column('labels', 'length')
    op.drop_column('labels', 'label_number')
    op.drop_column('labels', 'name')
    op.drop_column('labels', 'upc_code')
    op.drop_constraint(None, 'formulas', type_='foreignkey')
    op.drop_column('formulas', 'formula_link_type_id')
    op.drop_column('formulas', 'title')
    op.drop_constraint(None, 'combination_mapper', type_='foreignkey')
    op.drop_constraint(None, 'combination_mapper', type_='foreignkey')
    op.drop_column('combination_mapper', 'equipment_id')
    op.drop_column('combination_mapper', 'category_id')
    op.drop_constraint(None, 'codes', type_='foreignkey')
    op.drop_constraint(None, 'codes', type_='foreignkey')
    op.drop_constraint(None, 'codes', type_='foreignkey')
    op.drop_column('codes', 'created_at')
    op.drop_column('codes', 'adopted_at')
    op.drop_column('codes', 'state_id')
    op.drop_column('codes', 'issuing_body')
    op.drop_column('codes', 'applicable_code_category_id')
    op.drop_column('codes', 'edition')
    op.drop_column('codes', 'description')
    op.drop_column('codes', 'title')
    op.drop_column('codes', 'code_amendments')
    op.alter_column('code_types', 'key',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.drop_column('code_types', 'title')
    op.alter_column('ahjs', 'state_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('ahjs', 'ahj_name',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.drop_column('ahjs', 'created_at')
    op.drop_column('ahjs', 'website')
    op.drop_column('ahjs', 'email')
    op.drop_column('ahjs', 'phone')
    op.drop_column('ahjs', 'jurisdiction_type')
    op.drop_column('ahjs', 'fireset_back')
    op.drop_column('ahjs', 'city')
    op.drop_column('ahjs', 'county')
    op.drop_column('ahjs', 'name')
    # ### end Alembic commands ###
